import React from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { Shield, HelpCircle, Code, CheckSquare, Settings } from 'lucide-react';
import { WhyChip } from '../../../design/primitives';

interface StageProps {
  number: number;
  title: string;
  description: string;
  colorClass: string;
  bgLightClass: string;
  icon: React.ReactNode;
  preview: React.ReactNode;
}

export const HowItWorks: React.FC = () => {
  const prefersReducedMotion = useReducedMotion();

  const containerVariants = {
    hidden: {},
    visible: {
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  const stageVariants = {
    hidden: { opacity: 0, y: prefersReducedMotion ? 0 : 30 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.6, ease: 'easeOut' as const },
    },
  };

  const stages: StageProps[] = [
    {
      number: 1,
      title: 'Activity Telemetry Feeds In',
      description: 'Drishta safely integrates with your LMS portal (grades, attendance) and developer activities (GitHub commits, LeetCode progress).',
      colorClass: 'text-text',
      bgLightClass: 'bg-surface-2 border-line',
      icon: <Code className="w-5 h-5 text-text-dim" />,
      preview: (
        <div className="flex flex-wrap gap-2 justify-center py-4">
          <span className="text-[10px] font-mono px-2 py-1 bg-surface border border-line rounded-full shadow-sm text-text flex items-center gap-1.5 animate-pulse">
            <span className="w-1.5 h-1.5 rounded-full bg-decide" />
            LMS Canvas Sync
          </span>
          <span className="text-[10px] font-mono px-2 py-1 bg-surface border border-line rounded-full shadow-sm text-text flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-guard" />
            GitHub Commits
          </span>
          <span className="text-[10px] font-mono px-2 py-1 bg-surface border border-line rounded-full shadow-sm text-text flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-speak" />
            LeetCode API
          </span>
        </div>
      ),
    },
    {
      number: 2,
      title: 'The Core Decides, In the Open',
      description: 'The explainable system calculates risk standing using visible data parameters. Transparency means every risk assessment lists its precise math.',
      colorClass: 'text-decide border-decide/35',
      bgLightClass: 'bg-decide-lo border-decide/20',
      icon: <Settings className="w-5 h-5 text-decide" />,
      preview: (
        <div className="space-y-2 py-2">
          <div className="flex items-center justify-between text-xs border-b border-line pb-1">
            <span className="text-text-dim uppercase font-mono text-[9px]">Decision Standing</span>
            <span className="font-mono text-decide font-bold">72 / 100</span>
          </div>
          <WhyChip source="decide" className="w-full text-left py-1 text-[10px] bg-surface border border-line rounded shadow-sm text-text">
            Graph accuracy fell by 18% in Discrete Math
          </WhyChip>
        </div>
      ),
    },
    {
      number: 3,
      title: 'Your Mentor Speaks',
      description: 'An AI mentor synthesizes recommendations and explains confusing concepts. This model does not write grades or decide your standing.',
      colorClass: 'text-speak border-speak/35',
      bgLightClass: 'bg-speak-lo border-speak/20',
      icon: <HelpCircle className="w-5 h-5 text-speak" />,
      preview: (
        <div className="text-left space-y-1.5 py-1">
          <div className="p-2.5 bg-surface border border-line border-l-[3px] border-l-speak rounded text-[10px] text-text leading-snug">
            <p className="font-semibold text-speak font-mono uppercase text-[8px] tracking-wider mb-1">LLM Suggestion</p>
            <p className="font-medium text-text">"Let's practice 3 graph proof cards today."</p>
            <span className="block text-[8px] text-text-dim mt-1.5 leading-tight">
              ▎ Generated by AI layer. Not a formal record.
            </span>
          </div>
          <span className="block text-[8px] text-speak font-semibold tracking-tight text-center">
            * Never decides risk or grades
          </span>
        </div>
      ),
    },
    {
      number: 4,
      title: 'You Receive Your Plan',
      description: 'Drishta compiles a daily list of target review topics, practice proofs, and spaced-repetition cards directly in your dashboard.',
      colorClass: 'text-text-dim border-line',
      bgLightClass: 'bg-surface-2 border-line',
      icon: <CheckSquare className="w-5 h-5 text-text-dim" />,
      preview: (
        <div className="space-y-2 py-2 text-left max-w-[280px] mx-auto">
          <div className="flex items-center space-x-2 text-xs opacity-80">
            <span className="w-3.5 h-3.5 rounded-full border border-decide flex items-center justify-center text-[9px] text-white bg-decide font-bold">✓</span>
            <span className="font-medium text-text truncate line-through">Review Graph Isomorphism</span>
          </div>
          <div className="flex items-center space-x-2 text-xs">
            <span className="w-3.5 h-3.5 rounded-full border border-line bg-surface" />
            <span className="font-medium text-text truncate">Practice Red-Black Trees</span>
          </div>
        </div>
      ),
    },
    {
      number: 5,
      title: 'A Human Has the Final Say',
      description: 'Severe intervention plans are reviewed by faculty. No automated action is taken on your grades without an academic advisor approval.',
      colorClass: 'text-guard border-guard/35',
      bgLightClass: 'bg-guard-lo border-guard/20',
      icon: <Shield className="w-5 h-5 text-guard" />,
      preview: (
        <div className="space-y-1.5 py-2 text-center">
          <span className="inline-block text-[9px] px-2 py-0.5 bg-guard-lo border border-guard/35 text-guard rounded-full font-bold font-mono">
            FACULTY LEVEL OVERRIDE
          </span>
          <p className="text-[10px] text-text-dim leading-snug">
            Advisor confirmed counseling checklist mapping.
          </p>
        </div>
      ),
    },
  ];

  return (
    <section id="how-it-works" className="py-24 bg-surface border-b border-line relative overflow-hidden">
      <div className="max-w-6xl mx-auto px-6 space-y-16">
        {/* Section Header */}
        <div className="max-w-xl mx-auto text-center space-y-3">
          <span className="text-xs uppercase font-mono tracking-widest text-decide block">Engine Workflow</span>
          <h2 className="text-3xl font-display font-medium text-text">
            How Drishta <span className="text-decide italic">Works</span>
          </h2>
          <p className="text-sm text-text-dim leading-relaxed">
            Drishta pairs state-of-the-art predictive telemetry models with transparent human-in-the-loop oversight. Here is how your path is compiled.
          </p>
        </div>

        {/* Steps Grid / Timeline */}
        <motion.div 
          className="grid grid-cols-1 lg:grid-cols-5 gap-8 relative z-10"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-60px' }}
        >
          {stages.map((stage, idx) => (
            <motion.div 
              key={stage.number}
              variants={stageVariants}
              className="relative flex flex-col justify-between p-5 bg-surface border border-line rounded-xl shadow-[0_4px_12px_rgba(0,0,0,0.02)] hover:shadow-[0_8px_20px_rgba(0,0,0,0.06)] transition-all duration-300"
            >
              {/* Stepper connections indicator (Desktop only) */}
              {idx < 4 && !prefersReducedMotion && (
                <div className="hidden lg:block absolute top-12 left-full w-8 h-[1px] bg-decide/30 z-0" />
              )}

              {/* Icon / Number Header */}
              <div className="flex items-center justify-between pb-3">
                <div className={`p-2.5 rounded-full border ${stage.bgLightClass} flex items-center justify-center shrink-0`}>
                  {stage.icon}
                </div>
                <span className="text-xs font-mono font-bold text-line">0{stage.number}</span>
              </div>

              {/* Text Area */}
              <div className="space-y-2 mt-4 flex-1">
                <h3 className="text-sm font-semibold text-text leading-snug">{stage.title}</h3>
                <p className="text-[11.5px] text-text-dim leading-relaxed">{stage.description}</p>
              </div>

              {/* Live Simulated Preview Sub-Panel */}
              <div className={`mt-6 p-3 rounded-xl border text-center ${stage.bgLightClass} overflow-hidden shadow-inner`}>
                {stage.preview}
              </div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};

