import React from 'react';
import {
  Flame,
  Shield,
  CheckCircle,
  HelpCircle,
  Info,
  ArrowUpRight,
  ArrowDownRight,
  Minus
} from 'lucide-react';
import { Metric, WhyChip, RiskBand, KindTag, SegmentedBar } from '../design/primitives';
import { BentoCard } from '../design/bento';
import { ContributionStrip } from '../design/charts';
import type { StudentRisk, DailyTarget, Intervention, TopicMemory, StudentState } from '../api/schemas';

// 1. StreakPip - shows consecutive goals met
export const StreakPip: React.FC<{ streak: number }> = ({ streak }) => {
  return (
    <div className="flex items-center space-x-1.5 px-3 py-1 bg-speak-lo border border-speak/20 rounded-full text-speak" title="Goal Met Streak">
      <Flame className="w-4 h-4 fill-speak/20" />
      <Metric value={streak} className="text-speak text-xs font-bold" />
      <span className="text-[10px] uppercase font-semibold tracking-wider text-speak/80 ml-0.5">days</span>
    </div>
  );
};

// 2. RiskCard - displays risk status, reasons, and component bars (Reskinned as StatCard)
interface RiskCardProps {
  risk: StudentRisk;
  showBreakdown?: boolean;
  className?: string;
}

export const RiskCard: React.FC<RiskCardProps> = ({ risk, showBreakdown = true, className = '' }) => {
  const isHigh = risk.score > 70;
  const isMed = risk.score > 40 && risk.score <= 70;
  
  const borderGlow = isHigh 
    ? 'border-t-4 border-t-risk-high'
    : isMed 
      ? 'border-t-4 border-t-risk-med'
      : 'border-t-4 border-t-risk-low';

  return (
    <BentoCard size="none" className={`${borderGlow} ${className}`}>
      <div className="flex items-start justify-between">
        <div>
          <span className="text-[10px] uppercase tracking-wider font-mono text-text-dim block">Mentorship Standing</span>
          <h3 className="text-sm font-semibold text-text mt-1">Calculated Status</h3>
        </div>
        <div className="text-right">
          <div className="flex items-baseline justify-end space-x-1">
            <Metric value={risk.score} className="text-3xl font-bold font-mono" />
            <span className="text-xs text-text-dim">/100</span>
          </div>
          <RiskBand score={risk.score} className="mt-1" />
        </div>
      </div>

      <div className="mt-5 space-y-2">
        <span className="text-[10px] uppercase tracking-wider font-mono text-text-dim block">Explainable Factors</span>
        {risk.reasons.map((reason, idx) => (
          <WhyChip key={idx} source="decide" className="w-full text-left">
            {reason}
          </WhyChip>
        ))}
      </div>

      {showBreakdown && risk.components && (
        <div className="mt-6 pt-5 border-t border-line">
          <span className="text-[10px] uppercase tracking-wider font-mono text-text-dim block mb-3">Model Vectors</span>
          <SegmentedBar components={risk.components} />
        </div>
      )}
    </BentoCard>
  );
};

// 3. MentorMessage - LLM Phrased voice encouragement block
export const MentorMessage: React.FC<{ message: string; className?: string }> = ({ message, className = '' }) => {
  return (
    <div className={`p-4 bg-speak-lo border-l-[3px] border-speak rounded-r-md text-sm text-text relative ${className}`}>
      <div className="absolute top-2 right-2 text-speak/40">
        <span className="text-[10px] uppercase font-bold tracking-widest font-mono">LLM Voice</span>
      </div>
      <div className="flex items-start space-x-2.5">
        <div className="mt-0.5 p-1 bg-speak/10 rounded">
          <HelpCircle className="w-4 h-4 text-speak" />
        </div>
        <div>
          <p className="leading-relaxed pr-8">{message}</p>
          <div className="mt-2">
            <span className="text-[11px] text-speak font-mono">▎ Phrased response generated by AI layer. Not a formal record.</span>
          </div>
        </div>
      </div>
    </div>
  );
};

// 4. MissionRow - Checkable task item with KindTag and WhyChip
interface MissionRowProps {
  mission: DailyTarget;
  onToggle: (completed: boolean) => void;
  isPending?: boolean;
}

export const MissionRow: React.FC<MissionRowProps> = ({ mission, onToggle, isPending = false }) => {
  return (
    <div 
      className={`flex flex-col md:flex-row md:items-center justify-between p-4 bg-surface-2 border border-line rounded-lg transition-all duration-200 hover:bg-surface-2/80 ${
        mission.completed ? 'opacity-65' : ''
      }`}
    >
      <div className="flex items-start space-x-3 flex-1 min-w-0">
        <button
          onClick={() => !isPending && onToggle(!mission.completed)}
          disabled={isPending}
          className={`mt-0.5 w-5 h-5 rounded border flex items-center justify-center transition-all ${
            mission.completed 
              ? 'bg-decide border-decide text-white' 
              : 'border-line hover:border-decide bg-surface'
          } ${isPending ? 'opacity-50 cursor-wait' : 'cursor-pointer'}`}
          aria-label={mission.completed ? 'Mark task incomplete' : 'Mark task complete'}
        >
          {mission.completed && <CheckCircle className="w-3.5 h-3.5 fill-current text-white" />}
        </button>
        <div className="flex-1 min-w-0">
          <p className={`text-sm text-text font-medium leading-snug ${mission.completed ? 'line-through text-text-dim' : ''}`}>
            {mission.task}
          </p>
          <div className="mt-2 flex flex-wrap gap-2 items-center">
            <KindTag kind={mission.kind} />
            <WhyChip source={mission.why_source} className="text-[10px] py-0.5 px-2">
              {mission.why}
            </WhyChip>
          </div>
        </div>
      </div>
    </div>
  );
};

// 5. InterventionBanner - Governance Intervention notice
export const InterventionBanner: React.FC<{
  intervention: Intervention;
  onActionClick?: () => void;
  className?: string;
}> = ({ intervention, onActionClick, className = '' }) => {
  // Governance guards are colored Green
  return (
    <div className={`p-4 bg-guard-lo border border-guard/30 rounded-lg relative ${className}`}>
      <div className="flex items-start justify-between space-x-4">
        <div className="flex items-start space-x-3">
          <div className="mt-0.5 p-1 bg-guard/10 rounded">
            <Shield className="w-4 h-4 text-guard" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <span className="text-[11px] uppercase tracking-wider text-guard font-bold">Governance Safety Intervention</span>
              {intervention.approved ? (
                <span className="text-[10px] px-1.5 py-0.2 bg-guard/20 border border-guard/30 text-guard rounded">Faculty Approved</span>
              ) : (
                <span className="text-[10px] px-1.5 py-0.2 bg-speak-lo border border-speak/30 text-speak rounded">Pending Override</span>
              )}
            </div>
            <h4 className="text-sm font-semibold text-text mt-1">{intervention.action}</h4>
            <div className="mt-2">
              <WhyChip source="decide" className="text-[10px] py-0.5 px-2">
                {intervention.why}
              </WhyChip>
            </div>
            {intervention.note && (
              <div className="mt-2 text-xs text-text-dim italic bg-surface/70 p-2 rounded border border-line">
                Faculty Note: {intervention.note}
              </div>
            )}
          </div>
        </div>
        {onActionClick && !intervention.approved && (
          <button 
            onClick={onActionClick}
            className="px-3 py-1.5 bg-guard text-white hover:bg-guard/90 rounded text-xs font-bold transition cursor-pointer shrink-0"
          >
            Review Levers
          </button>
        )}
      </div>
    </div>
  );
};

// 6. ReviewCard - Spaced repetition review memory recall input (0-5 self assessment)
interface ReviewCardProps {
  memory: TopicMemory;
  onGrade: (grade: number) => void;
  isPending?: boolean;
}

export const ReviewCard: React.FC<ReviewCardProps> = ({ memory, onGrade, isPending = false }) => {
  return (
    <BentoCard size="none" className="space-y-4">
      <div>
        <div className="flex items-center justify-between">
          <span className="text-xs text-decide font-semibold tracking-wide uppercase">{memory.subject}</span>
        </div>
        <h4 className="text-base font-semibold text-text mt-1">{memory.topic}</h4>
      </div>

      <div className="pt-4 border-t border-line mt-3">
        <div className="grid grid-cols-2 sm:grid-cols-6 gap-1.5">
          {[0, 1, 2, 3, 4, 5].map((g) => {
            const isPassing = g >= 3;
            const activeColor = isPassing 
              ? 'hover:bg-guard hover:text-white hover:border-guard border-line text-guard' 
              : 'hover:bg-risk-high hover:text-white hover:border-risk-high border-line text-risk-high';

            const labels = ['Forgot', 'Hard', 'Struggled', 'Passed', 'Good', 'Perfect'];

            return (
              <button
                key={g}
                disabled={isPending}
                onClick={() => onGrade(g)}
                className={`py-2 text-center rounded border bg-surface-2 text-sm font-semibold transition cursor-pointer flex flex-col items-center justify-center ${activeColor} ${
                  isPending ? 'opacity-40 cursor-wait' : ''
                }`}
                title={`Grade ${g}: ${labels[g]}`}
              >
                <span className="font-mono text-base">{g}</span>
                <span className="text-[9px] font-normal font-sans opacity-80 mt-0.5">{labels[g]}</span>
              </button>
            );
          })}
        </div>
      </div>
    </BentoCard>
  );
};

// 7. EmptyState - illustrated helper when lists are empty
export const EmptyState: React.FC<{
  title: string;
  description: string;
  action?: React.ReactNode;
}> = ({ title, description, action }) => {
  return (
    <div className="p-8 text-center bg-surface-2 border border-line rounded-xl space-y-3">
      <div className="inline-flex p-3 bg-surface border border-line rounded-full text-text-dim">
        <Info className="w-6 h-6" />
      </div>
      <div className="space-y-1 max-w-md mx-auto">
        <h4 className="text-sm font-semibold text-text">{title}</h4>
        <p className="text-xs text-text-dim leading-relaxed">{description}</p>
      </div>
      {action && <div className="pt-2">{action}</div>}
    </div>
  );
};

// 8. Custom Toast Notification Context
interface ToastMessage {
  id: string;
  title: string;
  message: string;
  type?: 'decide' | 'speak' | 'guard' | 'error';
}

const ToastContext = React.createContext<{
  toast: (title: string, message: string, type?: 'decide' | 'speak' | 'guard' | 'error') => void;
} | null>(null);

export const useToast = () => {
  const context = React.useContext(ToastContext);
  if (!context) throw new Error('useToast must be used within ToastProvider');
  return context;
};

export const ToastProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [toasts, setToasts] = React.useState<ToastMessage[]>([]);

  const toast = React.useCallback(
    (title: string, message: string, type: 'decide' | 'speak' | 'guard' | 'error' = 'decide') => {
      const id = Math.random().toString(36).slice(2);
      setToasts((prev) => [...prev, { id, title, message, type }]);
      setTimeout(() => {
        setToasts((prev) => prev.filter((t) => t.id !== id));
      }, 4000);
    },
    []
  );

  return (
    <ToastContext.Provider value={{ toast }}>
      {children}
      {/* Toast container floating on screen */}
      <div className="fixed bottom-5 right-5 z-50 flex flex-col space-y-2 max-w-md w-full px-4 md:px-0">
        {toasts.map((t) => {
          let borderType = 'border-l-4 border-l-decide';
          if (t.type === 'speak') borderType = 'border-l-4 border-l-speak';
          if (t.type === 'guard') borderType = 'border-l-4 border-l-guard';
          if (t.type === 'error') borderType = 'border-l-4 border-l-risk-high';

          return (
            <div
              key={t.id}
              className={`p-4 rounded-[12px] shadow-lg bg-surface border border-line flex items-start space-x-3 transition-all duration-300 animate-slide-in ${borderType}`}
            >
              <div className="flex-1">
                <h5 className="text-xs font-bold uppercase tracking-wider text-text">{t.title}</h5>
                <p className="text-xs text-text-dim mt-1 leading-snug">{t.message}</p>
              </div>
              <button
                onClick={() => setToasts((prev) => prev.filter((item) => item.id !== t.id))}
                className="text-text-dim hover:text-text text-xs"
              >
                ×
              </button>
            </div>
          );
        })}
      </div>
    </ToastContext.Provider>
  );
};

// 9. CodingActivityCard - displays git & leetcode commits/solved counts
interface CodingActivityCardProps {
  state: StudentState;
}

export const CodingActivityCard: React.FC<CodingActivityCardProps> = ({ state }) => {
  const isRecentlyActive = state.activity.days_since_commit <= 7 || state.days_since_leetcode <= 7;
  const borderClass = isRecentlyActive
    ? 'border border-guard/30 bg-guard-lo'
    : 'border border-line bg-surface';

  const latestWeekCommits = state.contribution_weeks[state.contribution_weeks.length - 1]?.commit_count || 0;

  return (
    <BentoCard size="none" className={`p-4 space-y-4 rounded-xl ${borderClass}`}>
      <div className="flex justify-between items-center">
        <div>
          <h3 className="text-xs font-bold text-text uppercase tracking-wider">Coding Activity Signal</h3>
          <span className="text-[10px] text-text-dim">Git Commits & LeetCode Submissions</span>
        </div>
        {isRecentlyActive ? (
          <span className="text-[10.5px] bg-guard text-white px-2 py-0.5 rounded font-mono font-bold uppercase">
            Active
          </span>
        ) : (
          <span className="text-[10.5px] bg-surface-2 text-text-dim px-2 py-0.5 rounded font-mono font-bold uppercase border border-line">
            Stale
          </span>
        )}
      </div>

      <div className="grid grid-cols-2 gap-4">
        {/* LeetCode count */}
        <div className="space-y-1">
          <span className="text-[10px] text-text-dim uppercase font-mono">LeetCode Solved</span>
          <div className="flex items-baseline space-x-1">
            <Metric value={state.leetcode_solved_count} className="text-xl font-bold" />
            <span className="text-[10px] text-text-dim font-medium ml-1">problems</span>
          </div>
        </div>

        {/* LeetCode freshness */}
        <div className="space-y-1">
          <span className="text-[10px] text-text-dim uppercase font-mono">Last Submission</span>
          <div className="flex items-baseline space-x-1">
            <Metric value={state.days_since_leetcode} className="text-xl font-bold" />
            <span className="text-[10px] text-text-dim font-medium ml-1">days ago</span>
          </div>
        </div>
      </div>

      {/* Contribution Grid */}
      <div className="space-y-2 pt-2 border-t border-line">
        <div className="flex justify-between items-center">
          <span className="text-[10px] text-text-dim uppercase font-mono">Commit Calendar</span>
          <span className="text-[10px] font-mono text-text-dim">12w History</span>
        </div>
        <ContributionStrip weeks={state.contribution_weeks} />
      </div>

      {/* Status String */}
      <div className="text-[10.5px] text-text-dim leading-snug pt-1 font-mono">
        Last push <Metric value={state.activity.days_since_commit} className="font-bold" />d ago ·{' '}
        <Metric value={latestWeekCommits} className="font-bold" /> commits this week
      </div>
    </BentoCard>
  );
};

// 10. ListRow - dot + label + value + trend row
interface ListRowProps {
  dotColorClass: string;
  label: string;
  subLabel?: string;
  value: string | number;
  trend?: 'improving' | 'declining' | 'stable';
  onClick?: () => void;
  className?: string;
}

export const ListRow: React.FC<ListRowProps> = ({
  dotColorClass,
  label,
  subLabel,
  value,
  trend,
  onClick,
  className = '',
}) => {
  const renderTrendIcon = () => {
    if (!trend) return null;
    if (trend === 'improving') {
      return <ArrowUpRight className="w-3.5 h-3.5 text-guard shrink-0" />;
    }
    if (trend === 'declining') {
      return <ArrowDownRight className="w-3.5 h-3.5 text-risk-high shrink-0" />;
    }
    return <Minus className="w-3.5 h-3.5 text-text-dim shrink-0" />;
  };

  return (
    <div
      onClick={onClick}
      className={`flex items-center justify-between py-2.5 px-4 hover:bg-surface-2/50 transition-colors ${
        onClick ? 'cursor-pointer' : ''
      } ${className}`}
    >
      <div className="flex items-center space-x-3 min-w-0">
        <span className={`w-2 h-2 rounded-full ${dotColorClass} shrink-0`} />
        <div className="min-w-0">
          <p className="text-xs font-semibold text-text truncate">{label}</p>
          {subLabel && <p className="text-[10px] text-text-dim truncate">{subLabel}</p>}
        </div>
      </div>
      <div className="flex items-center space-x-2 text-right shrink-0">
        <Metric value={value} className="text-xs font-bold font-mono" />
        {renderTrendIcon()}
      </div>
    </div>
  );
};

// 11. ListPanel - Preline referral traffic list panel layout wrapper
interface ListPanelProps {
  title: string;
  children: React.ReactNode;
  className?: string;
}

export const ListPanel: React.FC<ListPanelProps> = ({ title, children, className = '' }) => {
  return (
    <BentoCard size="none" className={`p-0 overflow-hidden ${className}`}>
      <div className="px-4 py-3 border-b border-line bg-surface-2/50">
        <span className="text-[10px] uppercase font-mono tracking-wider text-text-dim block">
          {title}
        </span>
      </div>
      <div className="divide-y divide-line bg-surface/50">
        {children}
      </div>
    </BentoCard>
  );
};

// 12. ChartCard - GPA Projection SVG Chart Panel
interface ChartCardProps {
  title: string;
  value: string | number;
  caption: string;
  chartData: { subject: string; score: number }[];
  className?: string;
}

export const ChartCard: React.FC<ChartCardProps> = ({
  title,
  value,
  caption,
  chartData,
  className = '',
}) => {
  const height = 120;
  const width = 450;
  const padding = 20;

  const max = 100;
  const min = 0;
  const range = max - min;

  const coords = chartData.map((d, i) => {
    const x = padding + (i / (chartData.length - 1)) * (width - 2 * padding);
    const y = height - padding - ((d.score - min) / range) * (height - 2 * padding);
    return { x, y, subject: d.subject, score: d.score };
  });

  const pathD = coords.map((c, i) => `${i === 0 ? 'M' : 'L'} ${c.x} ${c.y}`).join(' ');
  const areaD = coords.length > 0 
    ? `${pathD} L ${coords[coords.length - 1].x} ${height - padding} L ${coords[0].x} ${height - padding} Z`
    : '';

  return (
    <BentoCard size="none" className={`p-6 space-y-6 ${className}`}>
      <div className="flex items-start justify-between border-b border-line pb-4">
        <div>
          <span className="text-[10px] uppercase font-mono tracking-wider text-text-dim block">
            {title}
          </span>
          <div className="flex items-baseline space-x-2 mt-1">
            <Metric value={value} className="text-3xl font-bold font-mono" />
            <span className="text-[10px] text-text-dim font-mono">on 4.0 scale</span>
          </div>
          <span className="text-[10px] text-speak font-semibold uppercase block mt-1 font-mono">
            {caption}
          </span>
        </div>
        <div className="text-[9px] uppercase font-mono tracking-wider text-text-dim bg-surface-2 px-2.5 py-1 rounded border border-line">
          Forecast Active
        </div>
      </div>

      <div className="space-y-4">
        <div className="relative h-[130px] w-full border border-line bg-surface-2/50 rounded-lg p-2 overflow-hidden">
          <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-full overflow-visible">
            <line x1={padding} y1={height/2} x2={width-padding} y2={height/2} stroke="var(--line)" strokeDasharray="3 3" />
            
            {areaD && (
              <path
                d={areaD}
                fill="url(#chart-gradient)"
                opacity="0.15"
              />
            )}

            {pathD && (
              <path
                d={pathD}
                fill="none"
                stroke="var(--color-decide)"
                strokeWidth="2.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            )}

            {coords.map((c, i) => (
              <g key={i}>
                <circle
                  cx={c.x}
                  cy={c.y}
                  r="4"
                  fill="white"
                  stroke="var(--color-decide)"
                  strokeWidth="2"
                />
                <text
                  x={c.x}
                  y={c.y - 8}
                  textAnchor="middle"
                  className="font-mono text-[9px] font-bold fill-text"
                >
                  {c.score}%
                </text>
              </g>
            ))}

            <defs>
              <linearGradient id="chart-gradient" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="var(--color-decide)" />
                <stop offset="100%" stopColor="var(--color-decide)" stopOpacity="0" />
              </linearGradient>
            </defs>
          </svg>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-2 border-t border-line">
          {coords.map((c, i) => (
            <div key={i} className="text-center font-mono text-[9px]">
              <span className="text-text-dim block truncate">{c.subject}</span>
              <span className="font-bold text-text mt-0.5 block">{c.score}%</span>
            </div>
          ))}
        </div>
      </div>
    </BentoCard>
  );
};

